export const CAR_LIST = [
  {
    carName: "Alto",
    img: "/images/alto.webp",
    engine: "796 cc",
    power: "35.3 @6000 rpm",
    fuelTank: "32L",
    torque: "69Nm @3500rpm",
    model: "VXI+",
    category: "Hatchback",
    airBags: "2",
    wheelBase: "2360mm",
    segment: "Arena",
  },
  {
    carName: "Swift",
    img: "/images/swift.webp",
    engine: "1197cc",
    power: "66kW @6000 rpm",
    fuelTank: "37L",
    torque: "113Nm @4400 rpm",
    model: "ZXI+",
    category: "Hatchback",
    airBags: "2",
    wheelBase: "2450mm",
  },
  {
    carName: "Vitara Brezza",
    img: "/images/brezza.webp",
    engine: "1462cc",
    power: "77kW @6000 rpm",
    fuelTank: "48L",
    torque: "138Nm @4400 rpm",
    model: "ZXI+",
    category: "SUV",
    airBags: "2",
    wheelBase: "2550mm",
    segment: "Arena",
  },
  {
    carName: "Ertiga",
    img: "/images/ertiga.webp",
    engine: "1462cc",
    power: "77kW @6000 rpm",
    fuelTank: "45L",
    torque: "138Nm @4400 rpm",
    model: "ZXI+",
    category: "SUV",
    airBags: "2",
    wheelBase: "2740mm",
    segment: "Arena",
  },
  {
    carName: "Dzire",
    img: "/images/dezire.webp",
    engine: "1197cc",
    power: "66kW @6000 rpm",
    fuelTank: "37L",
    torque: "113Nm @4400 rpm",
    model: "ZXI+",
    category: "Sedan",
    airBags: "2",
    wheelBase: "2450mm",
    segment: "Arena",
  },
  {
    carName: "XL6",
    img: "/images/xl6.jpg",
    engine: "796 cc",
    power: "35.3 @6000 rpm",
    fuelTank: "32L",
    torque: "69Nm @3500rpm",
    model: "VXI+",
    category: "SUV",
    airBags: "2",
    wheelBase: "2360mm",
    segment: "Nexa",
  },
  {
    carName: "Baleno",
    img: "/images/baleno.jpg",
    engine: "1197cc",
    power: "66kW @6000 rpm",
    fuelTank: "37L",
    torque: "113Nm @4400 rpm",
    model: "ZXI+",
    category: "Hatchback",
    airBags: "2",
    wheelBase: "2450mm",
    segment: "Nexa",
  },
  {
    carName: "Ignis",
    img: "/images/ignis.webp",
    engine: "1462cc",
    power: "77kW @6000 rpm",
    fuelTank: "48L",
    torque: "138Nm @4400 rpm",
    model: "ZXI+",
    category: "SUV",
    airBags: "2",
    wheelBase: "2550mm",
    segment: "Nexa",
  },
  {
    carName: "Scross",
    img: "/images/scross.jpeg",
    engine: "1462cc",
    power: "77kW @6000 rpm",
    fuelTank: "45L",
    torque: "138Nm @4400 rpm",
    model: "ZXI+",
    category: "SUV",
    airBags: "2",
    wheelBase: "2740mm",
    segment: "Nexa",
  },
  {
    carName: "Ciaz",
    img: "/images/ciaz.webp",
    engine: "1197cc",
    power: "66kW @6000 rpm",
    fuelTank: "37L",
    torque: "113Nm @4400 rpm",
    model: "ZXI+",
    category: "Sedan",
    airBags: "2",
    wheelBase: "2450mm",
    segment: "Nexa",
  },
];
